[tool.black]
target-version = ["py38"]

[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

[tool.mypy]
ignore_missing_imports = true

# Avoid unexpected keyword argument error in config_flow.py
disable_error_code = "call-arg"
