set_parameter:
  name: Set parameter
  description: Set controller or mixer parameter value.
  target:
    device:
      integration: "plum_ecomax"
  fields:
    name:
      name: Name
      description: Name of the parameter
      example: "heating_set_temp"
      required: true
      selector:
        text:
    value:
      name: Value
      description: A value that parameter will be set to
      example: "65"
      required: true
      selector:
        text:

set_schedule:
  name: Set schedule
  description: Set device schedule.
  fields:
    name:
      name: Name
      description: Name of the schedule
      example: "heating"
      required: true
      selector:
        select:
          options:
            - "Heating"
            - "Water Heater"
    weekday:
      name: Weekday
      description: Weekday to set the schedule
      example: "monday"
      required: true
      selector:
        select:
          options:
            - "Monday"
            - "Tuesday"
            - "Wednesday"
            - "Thursday"
            - "Friday"
            - "Saturday"
            - "Sunday"
    state:
      name: State
      description: State at scheduled time
      example: false
      required: true
      selector:
        boolean:
    start:
      name: Start
      description: Time at which scheduled state will be set
      example: "00:00:00"
      required: false
      selector:
        time:
    end:
      name: End
      description: Time at which scheduled state will be cleared
      example: "12:00:00"
      required: false
      selector:
        time:

reset_meter:
  name: Reset meter
  description: Reset meter value.
  target:
    entity:
      integration: "plum_ecomax"
      device_class: "weight"

calibrate_meter:
  name: Calibrate meter
  description: Calibrate meter value.
  target:
    entity:
      integration: "plum_ecomax"
      device_class: "weight"
  fields:
    value:
      name: Value
      description: A value that meter will be set to
      example: "100"
      required: true
      selector:
        text:
