get_parameter:
  target:
    device:
      integration: "plum_ecomax"
  fields:
    name:
      example: "heating_target_temp"
      required: true
      selector:
        text:

set_parameter:
  target:
    device:
      integration: "plum_ecomax"
  fields:
    name:
      example: "heating_target_temp"
      required: true
      selector:
        text:
    value:
      example: "65"
      required: true
      selector:
        text:

get_schedule:
  fields:
    type:
      example: "heating"
      required: true
      selector:
        select:
          translation_key: "schedule_type"
          options:
            - "heating"
            - "water_heater"
    weekday:
      example: "monday"
      required: true
      selector:
        select:
          translation_key: "weekday"
          options:
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"

set_schedule:
  fields:
    type:
      example: "heating"
      required: true
      selector:
        select:
          translation_key: "schedule_type"
          options:
            - "heating"
            - "water_heater"
    weekday:
      example: "monday"
      required: true
      selector:
        select:
          translation_key: "weekday"
          options:
            - "monday"
            - "tuesday"
            - "wednesday"
            - "thursday"
            - "friday"
            - "saturday"
            - "sunday"
    state:
      example: false
      required: true
      selector:
        boolean:
    start:
      example: "00:00:00"
      required: false
      selector:
        time:
    end:
      example: "12:00:00"
      required: false
      selector:
        time:

reset_meter:
  target:
    entity:
      integration: "plum_ecomax"
      device_class: "plum_ecomax__meter"

calibrate_meter:
  target:
    entity:
      integration: "plum_ecomax"
      device_class: "plum_ecomax__meter"
  fields:
    value:
      example: "100"
      required: true
      selector:
        text:
