set_parameter:
  name: Set Parameter
  description: Set device parameter value.
  fields:
    name:
      name: Name
      description: Name of the parameter
      example: "heating_set_temp"
      required: true
      selector:
        text:
    value:
      name: Value
      description: A value that parameter will be set to
      example: "65"
      required: true
      selector:
        text:

update_capabilities:
  name: Update Capabilities
  description: Update device capability list.

reset_meter:
  name: Reset Meter
  description: Reset meter value.
  target:
    entity:
      device_class: "plum_ecomax__meter"

calibrate_meter:
  name: Calibrate Meter
  description: Calibrate meter value.
  target:
    entity:
      device_class: "plum_ecomax__meter"
  fields:
    value:
      name: Value
      description: A value that meter will be set to
      example: "100"
      required: true
      selector:
        text:
