name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyplumio pytest-homeassistant-custom-component aiohttp_cors mypy pylint flake8

      - name: Check typing
        run: |
          mypy .

      - name: Lint
        run: |
          pylint custom_components/plum_ecomax
          flake8 .

      - name: Run tests
        run: |
          coverage run -m pytest tests/
          coverage report -m

      - uses: paambaati/codeclimate-action@v3.2.0
        if: github.event_name != "pull_request"
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
