name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyplumio==0.4.10 pytest-homeassistant-custom-component psutil-home-assistant fnv-hash-fast aiohttp_cors mypy pylint flake8 flake8-pyproject black

      - name: Check typing
        run: |
          mypy .

      - name: Lint
        run: |
          black --check custom_components/plum_ecomax
          pylint custom_components/plum_ecomax
          flake8 .

      - name: Run tests
        run: |
          coverage run -m pytest tests/
          coverage report -m

      - if: github.event_name != 'pull_request'
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
