name: ci

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage pyplumio pytest-homeassistant-custom-component aiohttp_cors mypy

    - name: Type checking
      run: |
        mypy custom_components/plum_ecomax

    - name: Run tests
      run: |
        coverage run -m pytest tests/
        coverage report -m

    - uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: coverage xml
